from enum import Enum
from pydantic import BaseModel, Field


class IntentType(str, Enum):
    query = "query"                               # SELECT / read data
    crud = "crud"                                 # INSERT / UPDATE / DELETE
    table_creation = "table_creation"             # CREATE TABLE
    collection_creation = "collection_creation"   # CREATE MongoDB collection
    database_creation = "database_creation"       # CREATE DATABASE
    schema_management = "schema_management"       # ALTER / DROP / RENAME
    visualization = "visualization"               # chart / graph / plot
    explanation = "explanation"                   # describe schema, "what tables exist"
    hybrid_query = "hybrid_query"                 # spans both PostgreSQL and MongoDB


class TargetDB(str, Enum):
    postgresql = "postgresql"
    mongodb = "mongodb"
    both = "both"
    none = "none"


class IntentResult(BaseModel):
    intent: IntentType
    target_db: TargetDB
    entities: list[str] = Field(
        default_factory=list,
        description="Table or collection names referenced or implied by the request.",
    )
    confidence: float = Field(ge=0.0, le=1.0)
    requires_schema: bool = Field(
        description="True when the request needs schema context (columns, types) to execute."
    )
    explanation: str = Field(
        description="One sentence explaining the classification."
    )
    # Set by the classifier after LLM call — not generated by the model.
    nl_query: str = ""
